; Project-authored wizard translations; unspecified diagnostic messages fall back to Default.isl.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=0
DialogFontName=Microsoft YaHei UI
DialogFontSize=9
WelcomeFontName=Microsoft YaHei UI
WelcomeFontSize=18

[Messages]
SetupAppTitle=安装
SetupWindowTitle=%1 · 安装向导
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
InformationTitle=提示
ConfirmTitle=确认
ErrorTitle=错误
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)…
ButtonWizardBrowse=浏览(&R)…
ButtonNewFolder=新建文件夹(&M)
WelcomeLabel1=欢迎使用 [name] 安装向导
WelcomeLabel2=即将安装 [name/ver]。%n%n安装包包含独立窗口、演示环境与案例素材。真实检测所需的大模型稍后在软件内按指引配置。%n%n请先关闭已经运行的筑安智巡，再继续安装。
WizardLicense=使用授权
LicenseLabel=请阅读项目的使用授权说明。
LicenseLabel3=继续前请阅读以下协议。安装不会授予模型或第三方素材的额外使用权。
LicenseAccepted=我接受协议(&A)
LicenseNotAccepted=我不接受协议(&D)
WizardInfoBefore=安装前须知
InfoBeforeLabel=请了解演示环境、模型配置与数据保留方式。
InfoBeforeClickLabel=阅读完毕后，点击“下一步”继续。
WizardSelectDir=选择安装位置
SelectDirDesc=将 [name] 安装在哪里？
SelectDirLabel3=建议使用默认的当前用户目录。请选择专用子目录，不要选择工作资料的根目录。
SelectDirBrowseLabel=点击“下一步”使用当前目录，或点击“浏览”选择其他位置。
DiskSpaceMBLabel=至少需要 [mb] MB 的可用磁盘空间。
WizardSelectTasks=快捷方式
SelectTasksDesc=选择需要创建的快捷方式。
SelectTasksLabel2=开始菜单入口将自动创建；桌面快捷方式可以选择。
WizardReady=准备安装
ReadyLabel1=现在可以安装 [name]。
ReadyLabel2a=点击“安装”开始。点击“上一步”可以修改设置。
ReadyMemoDir=安装目录：
ReadyMemoGroup=开始菜单：
ReadyMemoTasks=附加任务：
WizardPreparing=正在准备
PreparingDesc=正在检查安装目录与窗口运行环境。
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候。
StatusExtractFiles=正在复制程序与演示素材…
StatusCreateIcons=正在创建快捷方式…
StatusCreateIniEntries=正在保存安装信息…
StatusCreateRegistryEntries=正在注册软件…
StatusSavingUninstall=正在准备卸载入口…
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=软件已安装，可以从开始菜单打开。
FinishedLabel=软件已安装，可通过开始菜单或桌面快捷方式打开。
ClickFinish=点击“完成”退出安装向导。
ExitSetupTitle=取消安装
ExitSetupMessage=安装尚未完成。现在退出？
ConfirmUninstall=确定卸载 %1？%n%n业务资料、模型与个人配置将保留。
UninstallStatusLabel=正在移除程序，请稍候。
UninstalledAll=%1 已卸载。保留的数据不会自动删除。
UninstallNotVerified=请先正常关闭软件和后台服务，再重试卸载。
ApplicationsFound=以下程序需要关闭：
